### ISSUE TITLE
Dramatically slow after upgrading Debian

### ISSUE THREAD

**Issue by Divetoxx** [6o6o/chainer-fast-neuralstyle#4]
Hi!
Could anyone help? After apt-get upgrade made by me in my Debian
I have found that generate.py works now 1800 sec instead of 20 sec earlier!
I am very sad now and understand nothing!
What is the reason of this Hell?
Help me please!

**Comment by 6o6o** [comment]
Were you using the GPU? If so, my guess would be that something with your CUDA installation got corrupt. Reinstall CUDA, cuDNN, Chainer and give it a go. And don't forget the `-g 0` flag

**Comment by Divetoxx** [comment]
No, I was not using the GPU, if I could use the GPU the time could be 2-3 sec, not 20 sec. I was using CPU only, intel i5. I can't understand why the time needed for 1 picture become 1800 sec! It's completely terrible.

**Comment by 6o6o** [comment]
Unfortunately I don't have much experience with CPU operation, so it's hard for me spot the culprit. Try upgrading Chainer and other dependent libs. Apart from this, I'm out of suggestions. Perhaps someone else can help you out.

**Comment by Divetoxx** [comment]
The problem is solved!
I have found that It's very, very important to install python-opencv AFTER installing chainer and pillow!
When python-opencv was installed before them I had to wait 30 minutes for 1 picture rendering!
When python-opencv was installed after them the time of rendering 1 picture was 20 seconds!
I didn't know this important detail! Now I know.

**Comment by 6o6o** [comment]
Good to know. Congrats!
